title: Welcome to my blog
author: Joshua Karki
email: jxk190049@utdallas.edu
description: > 
  In this site, you can browse my projects to get further insight
  on my portfolio and see if the skills I have to offer meet the 
  job requirements.

# social links
twitter_username: i do not have a twitter
github_username:  JoshuaKarki27

show_excerpts: false # set to false to remove excerpts on the homepage
theme: minima
